[package]
name = "non-std-event-stream-example"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
axum = "0.7"
async-stream = "0.3.6"
bytes = "1.11.0"
